In [2]:
import pandas as pd


In [4]:
data = pd.read_csv('datasets/titanic.csv')
data.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [5]:
data['male'] = pd.get_dummies(data['Sex'], drop_first=True)
data.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  \
0    male  22.0                        1                        0   7.2500   
1  female  38.0                        1                        0  71.2833   
2  female  26.0                        0                        0   7.9250   
3  female  35.0                        1                        0  53.1000   
4    male  35.0                        0                        0   8.0500   

   male  
0     1  
1     0  
2     0  
3     0  
4     1

In [6]:
data.drop(columns = ['Name', 'Sex'],inplace=True)
data.head()

Survived  Pclass   Age  Siblings/Spouses Aboard  Parents/Children Aboard  \
0         0       3  22.0                        1                        0   
1         1       1  38.0                        1                        0   
2         1       3  26.0                        0                        0   
3         1       1  35.0                        1                        0   
4         0       3  35.0                        0                        0   

      Fare  male  
0   7.2500     1  
1  71.2833     0  
2   7.9250     0  
3  53.1000     0  
4   8.0500     1

In [7]:
data.shape

(887, 7)

In [8]:
data_col = data.columns

### covariance 

In [74]:
from numpy import cov

In [58]:
def Relationship(df, cols):
    output =[]
    for i, col in enumerate(cols):
        if i == 6:
            break
        value = cov(df[col], df[cols[i+1]])
        output.append(value)
    return output

In [59]:
cov_relation = Relationship(data, data_col)
cov_relation

[array([[ 0.23717301, -0.13712109],
        [-0.13712109,  0.70000331]]),
 array([[  0.70000331,  -4.62557683],
        [ -4.62557683, 199.42829701]]),
 array([[199.42829701,  -4.64364838],
        [ -4.64364838,   1.22029261]]),
 array([[1.22029261, 0.36949822],
        [0.36949822, 0.65200119]]),
 array([[6.52001191e-01, 8.66131359e+00],
        [8.66131359e+00, 2.47825155e+03]]),
 array([[ 2.47825155e+03, -4.31462851e+00],
        [-4.31462851e+00,  2.28942767e-01]])]

# correlation

**Covariance** just gives the ``direction`` ,but **Correlation** gives the direction as well as ``strength`` of features.

### Pearson's Correlation
Usually Pearson is used widely eventhough it is sensitive to outliers.

IF data is Gausian then the data is linear.

Perason is more ``SENTITIVE`` to outliers.Unlike Spearman.

It refers to only **linear** data points...

In [1]:
from scipy.stats import pearsonr

In [13]:
def get_relation(df, cols):
    output =[]
    for i, col in enumerate(cols):
        if i == 6:
            break
        value, _ = pearsonr(df[col], df[cols[i+1]])
      
        output.append(value)
    return output

In [14]:
result = get_relation(data, data_col)
result

[-0.3365282999457141,
 -0.3914916127382422,
 -0.2976692313857061,
 0.414243940705179,
 0.21547003157589079,
 -0.18113703399703726]

### Spearman's Correlation Coeffiecent

It gives the **non-linearity** relationship between two varibles..Further 2 variables considered may have **non-Gausian distribution**.

If we are unsure about distribution and possible relationship between two variables then spearman's correlation is good to use...

#### Equation:
    r = 1 - [6 sum(d*d) / (n^3 - n)]
    
* ``n`` is the no. of observaitons
* ``d`` is the difference between two rankings formed by the 2 columns in a dataframe...       

In [71]:
from scipy.stats import spearmanr

In [72]:
def get_relation(df, cols):
    output =[]
    for i, col in enumerate(cols):
        if i == 6:
            break
        value, _ = spearmanr(df[col], df[cols[i+1]])
        output.append(value)
    return output

In [73]:
result = get_relation(data, data_col)
result

[-0.33764791930976135,
 -0.3879820094966259,
 -0.1992687071029132,
 0.44919804866893803,
 0.4092024096482796,
 -0.25796465147292236]